# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

os: Windows Server 2012 R2

# build version format
version: "{build}-{branch}"


init:
  - git config --global core.autocrlf input

# Set a known clone folder
clone_folder: C:\projects\zsclient

matrix:
  fast_finish: true

# branches
branches:
  only:
    - master
    
skip_tags: true
skip_commits:
  message: /\[\s*skip\s+ci\s*\]/    # Ignore messages with [skip ci]

platform: Any CPU

# Install scripts
install:
  ## Set PHP.
  - cinst php
  - SET PATH=C:\tools\php\;%PATH%
  - cd C:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="Europe/Berlin" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo output_buffering = Off >> php.ini
  - echo default_charset = UTF-8 >> php.ini

  - php -v
  - where php

  ## Set Composer.
  - cd C:\projects\zsclient
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar --version
  - php composer.phar install --dev --prefer-source

build_script:
  - php vendor/fabpot/php-cs-fixer/php-cs-fixer fix -v --dry-run --level=psr2 .
  - php vendor/phpunit/phpunit/phpunit -c module/Client/tests/phpunit.xml
  - php bin/zs-client.phar targetFileLocation 
  - php bin/build-zpk.php

test: off
deploy: off
